language: node_js
node_js: '8'
cache: yarn

before_script:
  - yarn setup
  - yarn build

script:
  - yarn test

after_success:
  - yarn docs

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
      branch: master
  - provider: npm
    email: mariandev96@gmail.com
    api_key: $NPM_API_KEY
    on:
      tags: true
      branch: master
